name: huntlab-smallrna
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - toml
  - pysam
  - biopython
  - matplotlib
  - cutadapt
  - fastqc
  - bbmap
  - unitas
  - bowtie2
  - samtools
