name: huntlab-smallrna
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - toml
  - pysam
  - biopython
  - gffutils
  - matplotlib
  - cutadapt
  - fastqc
  - bbmap
  - unitas
  - perl-archive-extract
  - bioconda/label/main::perl-lwp-simple
  - bowtie2
  - samtools
  - bedtools
  - pip
  - pip:
    - .

